import time
print("Starting the Program...")
print(" ")
time.sleep(4)
while "true":
    mainyear = time.strftime("%Y")
    ad = input("Your name ? : \n")
    print(" ")
    time.sleep(1)
    yıl = int(input ("Your birth year ? : \n"))
    print(" ")
    print("Please wait, calculating...")
    sonuc = int(mainyear) - int(yıl)
    
    time.sleep(3)
    print(" ")
    print(ad + ', your age is ' + '"' + str(sonuc) + '"')
    print(" ")
    time.sleep(2)
    print("--------------------------")